"""Declarative registry of every runnable task.

Adding a future function means adding one TaskSpec here: the nav entry,
settings form, surgical config save and subprocess run all come from this
data.  Nothing else in the GUI needs to change.

TASKS 的顺序即侧边栏的显示顺序。
"""

from __future__ import annotations

from GUI.core.paths import CONFIGS, SCRIPTS
from GUI.core.runner import TaskSpec
from GUI.widgets.forms import F

# 可复用的字段组 -------------------------------------------------------------


def camera_name_field(section="相机"):
    return F(
        "camera_name",
        "相机名称匹配",
        section=section,
        tip="相机设备名中包含的唯一子串, 程序自动查找 Windows DirectShow 或 Linux V4L2 设备",
    )


def camera_index_field(section="相机"):
    return F(
        "camera",
        "相机索引覆盖",
        kind="int_null",
        section=section,
        tip="填整数直接指定 OpenCV 相机索引, 覆盖名称匹配; null 用名称匹配",
    )


def frame_size_fields(section="相机"):
    return [
        F("frame_width", "请求图像宽", kind="int_null", section=section, unit="px"),
        F("frame_height", "请求图像高", kind="int_null", section=section, unit="px"),
    ]


def stage_serial_fields(section="位移台"):
    return [
        F("port", "串口", section=section, tip="如 COM3 或 /dev/lensdetect-stage"),
        F("baudrate", "波特率", kind="int", section=section),
        F(
            "x_lead_mm_per_rev",
            "X 导程",
            kind="float",
            section=section,
            unit="mm/转",
            step=0.1,
        ),
        F(
            "y_lead_mm_per_rev",
            "Y 导程",
            kind="float",
            section=section,
            unit="mm/转",
            step=0.1,
        ),
        F("x_slave_address", "X 从站地址", kind="int", section=section),
        F("y_slave_address", "Y 从站地址", kind="int", section=section),
    ]


# 功能顺序即侧边栏顺序 ---------------------------------------------------------

TASKS = [
    TaskSpec(
        id="height_check",
        nav_label="高度检测",
        glyph="↕",
        title="载具高度检测",
        subtitle="在固定 Zoom 和 Focus 下拍摄载具，通过白色矩形边框是否完整位于安全边界内判断高度是否合适。",
        script=SCRIPTS["height_check"],
        config=CONFIGS["height_check"],
        run_note=(
            "实时模式会读取对应 Zoom 的 PCB 自动对焦 focus/iris，控制镜头后拍摄并去畸变；"
            "启用自动居中时会移动位移台，填写离线图片后将跳过全部硬件。"
        ),
        fields=[
            F(
                "image",
                "离线图片",
                kind="str_null",
                section="检测输入",
                tip="null 使用相机实时拍摄；填写图片路径时只检测该图片",
            ),
            F(
                "margin",
                "安全边距比例",
                kind="float",
                section="检测参数",
                step=0.005,
                tip="相对于图像短边的比例，例如 0.02 表示保留 2% 安全边距",
            ),
            F(
                "small_zoom",
                "Zoom",
                kind="int",
                section="镜头",
                tip="focus/iris 从同 Zoom 的 PCB 自动对焦结果读取",
            ),
            F(
                "align_frame_center",
                "检测前自动居中",
                kind="bool",
                section="检测参数",
                tip="将首帧白色边框中心移动到当前分辨率的图像中心后重新拍摄",
            ),
            F("lens_device", "LensConnect 设备号", kind="int_null", section="镜头"),
            F("lens_no_init", "禁止自动初始化电机", kind="bool", section="镜头"),
            F(
                "lens_settle_seconds",
                "镜头稳定等待",
                kind="float",
                section="镜头",
                unit="s",
                step=0.1,
            ),
            F(
                "calibration",
                "标定汇总文件",
                kind="str_null",
                section="镜头",
                tip="null 使用 detection/calibration/output/calibrate.json",
            ),
            camera_name_field(),
            camera_index_field(),
            *frame_size_fields(),
            F(
                "keep_camera_autofocus",
                "保留相机自动对焦",
                kind="bool",
                section="相机",
            ),
            F(
                "camera_startup_discard_frames",
                "开启相机丢弃帧数",
                kind="int",
                section="相机",
            ),
            F("capture_discard_frames", "采集前丢弃帧数", kind="int", section="相机"),
            F(
                "capture_delay_seconds",
                "拍摄前等待",
                kind="float",
                section="相机",
                unit="s",
                step=0.1,
            ),
            *stage_serial_fields(),
            F("speed_rpm", "速度", kind="int", section="位移台", unit="rpm"),
            F(
                "timeout_seconds",
                "运动超时",
                kind="float",
                section="位移台",
                unit="s",
                step=0.5,
            ),
            F(
                "position_tolerance_mm",
                "到位容差",
                kind="float",
                section="位移台",
                unit="mm",
                step=0.005,
            ),
            F(
                "max_move_mm",
                "自动居中最大距离",
                kind="float",
                section="位移台",
                unit="mm",
                step=1.0,
            ),
            F(
                "x_limits",
                "X 软限位",
                kind="vec2_null",
                section="位移台",
                unit="mm",
            ),
            F(
                "y_limits",
                "Y 软限位",
                kind="vec2_null",
                section="位移台",
                unit="mm",
            ),
            F("save_raw", "保存原始图像", kind="bool", section="输出"),
            F(
                "output_dir",
                "输出目录",
                section="输出",
                tip="每次运行在其下新建时间戳子目录",
            ),
        ],
    ),
    TaskSpec(
        id="autofocus",
        nav_label="PCB自动对焦",
        glyph="⌖",
        title="PCB 自动对焦",
        subtitle="移动电动镜头 zoom/iris 后搜索最清晰的 focus 位置, 保存最佳对焦图像与完整评分日志。",
        script=SCRIPTS["autofocus"],
        config=CONFIGS["autofocus"],
        run_note=(
            "若启用了“交互 ROI”, 会弹出框选窗口: 拖拽选区, Enter 开始, "
            "Backspace 删除上一框, C 清空, Esc 取消。"
        ),
        fields=[
            F("device", "LensConnect 设备号", kind="int_null", section="镜头目标"),
            F("zoom", "zoom 目标", kind="int_null", section="镜头目标"),
            F("iris", "iris 目标", kind="int_null", section="镜头目标"),
            F(
                "skip_json_zoom",
                "跳过 zoom 移动",
                kind="bool",
                section="镜头目标",
                tip="true: 在当前位置搜索 focus",
            ),
            F("skip_json_iris", "跳过 iris 移动", kind="bool", section="镜头目标"),
            F("skip_autofocus", "跳过对焦直接拍照", kind="bool", section="镜头目标"),
            F("no_init", "禁止自动初始化电机", kind="bool", section="镜头目标"),
            camera_name_field(),
            *frame_size_fields(),
            F(
                "disable_camera_autofocus",
                "关闭相机自动对焦",
                kind="bool",
                section="相机",
                tip="避免相机 AF 与电动镜头互相干扰",
            ),
            F(
                "optimizer",
                "搜索算法",
                kind="enum",
                section="搜索算法",
                options=("golden-section", "coarse-to-fine"),
            ),
            F(
                "metric",
                "清晰度算法",
                kind="enum",
                section="搜索算法",
                options=("tenengrad", "laplacian", "brenner", "fft"),
            ),
            F(
                "focus_min",
                "搜索下限",
                kind="int_null",
                section="搜索算法",
                tip="null 用镜头支持的最小值",
            ),
            F("focus_max", "搜索上限", kind="int_null", section="搜索算法"),
            F("coarse_steps", "粗扫点数", kind="int", section="coarse-to-fine"),
            F(
                "fine_steps",
                "细扫点数",
                kind="int",
                section="coarse-to-fine",
                tip="0 跳过细扫",
            ),
            F(
                "fine_radius",
                "细扫半径",
                kind="float_null",
                section="coarse-to-fine",
                tip="null 自动用粗扫步距",
            ),
            F("early_stop", "提前停止", kind="bool", section="coarse-to-fine"),
            F(
                "early_stop_drop_count",
                "连降次数阈值",
                kind="int",
                section="coarse-to-fine",
            ),
            F(
                "early_stop_min_points",
                "最少扫描点",
                kind="int",
                section="coarse-to-fine",
            ),
            F(
                "early_stop_min_relative_drop",
                "最小相对下降",
                kind="float",
                section="coarse-to-fine",
                step=0.01,
            ),
            F("golden_tolerance", "停止阈值", kind="int", section="golden-section"),
            F(
                "golden_bracket_steps",
                "区间探测点数",
                kind="int",
                section="golden-section",
                tip="0 关闭",
            ),
            F(
                "golden_tie_relative_margin",
                "平局相对阈值",
                kind="float",
                section="golden-section",
                step=0.001,
            ),
            F(
                "golden_highres_auto",
                "4K 自动增强",
                kind="bool",
                section="golden-section",
            ),
            F("golden_max_iter", "最大迭代", kind="int", section="golden-section"),
            F("score_frames", "每位置评分帧数", kind="int", section="评分"),
            F(
                "aggregate",
                "多帧聚合",
                kind="enum",
                section="评分",
                options=("mean", "median"),
            ),
            F("discard_frames", "移动后丢弃帧数", kind="int", section="评分"),
            F("startup_discard_frames", "开启相机丢弃帧数", kind="int", section="评分"),
            F("settle", "移动后等待", kind="float", section="评分", unit="s", step=0.1),
            F(
                "score_max_side",
                "评分 ROI 最长边",
                kind="int",
                section="评分",
                unit="px",
            ),
            F(
                "roi",
                "评分 ROI",
                kind="str_null",
                section="评分",
                tip="x,y,width,height; null 用中心区域",
            ),
            F("interactive_roi", "交互选择 ROI", kind="bool", section="评分"),
            F(
                "interactive_roi_max_side",
                "交互预览缩放",
                kind="int",
                section="评分",
                unit="px",
            ),
            F("roi_scale", "中心 ROI 比例", kind="float", section="评分", step=0.05),
            F("blur_ksize", "评分模糊核", kind="int", section="评分"),
            F(
                "output_dir",
                "输出目录",
                section="输出",
                tip="每次运行在其下新建时间戳子目录",
            ),
        ],
    ),
    TaskSpec(
        id="lens",
        nav_label="相机内参标定",
        glyph="◉",
        title="相机内参标定 (棋盘格)",
        subtitle="在线连接相机采集棋盘格图像，计算相机内参与畸变系数。",
        script=SCRIPTS["lens"],
        config=CONFIGS["lens"],
        run_note=(
            "实时采集时将弹出相机预览窗口: "
            "空格/Enter 检测并保存当前帧, q/Q/Esc 结束采集并开始计算。"
        ),
        fields=[
            F(
                "board_cols",
                "棋盘内角点列数",
                kind="int",
                section="标定板",
                tip="内角点数量, 不是黑白方格数",
            ),
            F("board_rows", "棋盘内角点行数", kind="int", section="标定板"),
            F(
                "square_size",
                "方格边长",
                kind="float",
                section="标定板",
                unit="mm",
                step=0.1,
            ),
            F("square_unit", "边长单位", section="标定板", tip="仅记录, 不参与计算"),
            F("frames", "采集帧数", kind="int", section="采集"),
            F(
                "min_frames",
                "最少有效帧数",
                kind="int",
                section="采集",
                tip="少于该数量报错退出",
            ),
            F(
                "single_shot_capture",
                "单张拍摄模式",
                kind="bool",
                section="采集",
                tip="true: 每次只拍一张静态图; false: 实时预览",
            ),
            F(
                "live_preview_detect_on_key",
                "按键时才检测角点",
                kind="bool",
                section="采集",
                tip="true 可减少角点检测导致的预览卡顿",
            ),
            F("capture_dir", "原始图像保存目录", kind="str_null", section="采集"),
            F("debug_dir", "角点调试图目录", kind="str", section="采集"),
            camera_name_field(),
            *frame_size_fields(),
            F(
                "default_output_file",
                "结果输出文件",
                section="输出",
                tip="相对路径以项目根目录为基准",
            ),
            F(
                "default_log_file",
                "日志输出文件",
                kind="str_null",
                section="输出",
                tip="null 使用同名 .log 文件",
            ),
        ],
    ),
    TaskSpec(
        id="board",
        nav_label="标定板→像素标定",
        glyph="▨",
        title="标定板→像素仿射标定",
        subtitle="固定相机拍摄局部棋盘格, 拟合板平面 mm → 像素的仿射变换, 并记录位移台参考位姿。",
        script=SCRIPTS["board"],
        config=CONFIGS["board"],
        run_note=("弹出预览窗口后对准局部棋盘格: SPACE/ENTER 检测并接受, Q/ESC 取消。"),
        fields=[
            F(
                "board_cols",
                "局部内角点列数",
                kind="int",
                section="棋盘格局部视野",
                tip="只需图像内可见的矩形角点组, 不需整块板",
            ),
            F("board_rows", "局部内角点行数", kind="int", section="棋盘格局部视野"),
            F(
                "square_size",
                "方格边长",
                kind="float",
                section="棋盘格局部视野",
                unit="mm",
                step=0.1,
            ),
            F(
                "origin_x_mm",
                "原点 X",
                kind="float",
                section="棋盘格局部视野",
                unit="mm",
                step=0.1,
                tip="可见左上角内点对应的板坐标",
            ),
            F(
                "origin_y_mm",
                "原点 Y",
                kind="float",
                section="棋盘格局部视野",
                unit="mm",
                step=0.1,
            ),
            F(
                "column_axis",
                "列方向轴",
                kind="enum",
                section="棋盘格局部视野",
                options=("+x", "-x", "+y", "-y"),
            ),
            F(
                "row_axis",
                "行方向轴",
                kind="enum",
                section="棋盘格局部视野",
                options=("+x", "-x", "+y", "-y"),
            ),
            F(
                "ransac_threshold_px",
                "RANSAC 内点阈值",
                kind="float",
                section="仿射拟合",
                unit="px",
                step=0.1,
            ),
            F("ransac_iterations", "RANSAC 迭代次数", kind="int", section="仿射拟合"),
            F(
                "min_inlier_ratio",
                "最少内点比例",
                kind="float",
                section="仿射拟合",
                step=0.05,
            ),
            F("random_seed", "随机种子", kind="int", section="仿射拟合"),
            camera_name_field(),
            camera_index_field(),
            *frame_size_fields(),
            F("startup_discard_frames", "开启相机丢弃帧数", kind="int", section="相机"),
            F("keep_camera_autofocus", "保留相机自动对焦", kind="bool", section="相机"),
            F(
                "capture_now",
                "立即抓拍",
                kind="bool",
                section="相机",
                tip="true: 打开相机直接抓拍一帧, 不显示预览窗口",
            ),
            F(
                "record_stage_position",
                "记录位移台位置",
                kind="bool",
                section="位移台",
                tip="保存标定时的绝对位姿供定点移动复位使用",
            ),
            *stage_serial_fields(),
            F(
                "output",
                "结果输出文件",
                kind="str_null",
                section="输出",
                tip="null 在 working_data/board_pixel_affine 下建时间戳目录; 填写则必须是 .json 文件路径",
            ),
            F("log_output", "日志输出文件", kind="str_null", section="输出"),
            F(
                "annotated_output",
                "标注图输出文件",
                kind="str_null",
                section="输出",
                tip="填写则必须是 .png 文件路径",
            ),
        ],
    ),
    TaskSpec(
        id="stage",
        nav_label="位移台→像素标定",
        glyph="⇄",
        title="位移台指令→像素位移标定",
        subtitle="在两档 Zoom 下分别做相对运动采样，并各自拟合指令 mm → 像素的 2×2 矩阵。",
        script=SCRIPTS["stage"],
        config=CONFIGS["stage"],
        run_note="自动读取两档 Zoom 的 PCB 自动对焦 Focus，并依次移动镜头和位移台；运行期间请勿触碰工作台。",
        fields=[
            F(
                "start_position_mm",
                "标定起点",
                kind="vec2_null",
                section="公共采样",
                unit="mm",
                tip="null: 从当前位置直接开始, 不做初始绝对移动",
            ),
            F(
                "zoom_1",
                "Zoom 1",
                kind="int",
                section="Zoom 1 采样",
                tip="Focus 从同 Zoom 的 PCB 自动对焦结果精确读取",
            ),
            F(
                "zoom_1_x_step_mm",
                "X 步距列表",
                kind="float_list",
                section="Zoom 1 采样",
                unit="mm",
                tip="如 2, 4, 6; 每个值都会做正负两个方向的往返",
            ),
            F(
                "zoom_1_y_step_mm",
                "Y 步距列表",
                kind="float_list",
                section="Zoom 1 采样",
                unit="mm",
            ),
            F(
                "zoom_2",
                "Zoom 2",
                kind="int",
                section="Zoom 2 采样",
                tip="Focus 从同 Zoom 的 PCB 自动对焦结果精确读取",
            ),
            F(
                "zoom_2_x_step_mm",
                "X 步距列表",
                kind="float_list",
                section="Zoom 2 采样",
                unit="mm",
                tip="可按 Zoom 2 视野单独设置采样范围",
            ),
            F(
                "zoom_2_y_step_mm",
                "Y 步距列表",
                kind="float_list",
                section="Zoom 2 采样",
                unit="mm",
            ),
            F("lens_device", "LensConnect 设备号", kind="int_null", section="镜头"),
            F("lens_no_init", "禁止自动初始化电机", kind="bool", section="镜头"),
            F(
                "lens_settle_seconds",
                "镜头移动等待",
                kind="float",
                section="镜头",
                unit="s",
                step=0.1,
            ),
            F(
                "calibration",
                "标定汇总文件",
                kind="str_null",
                section="镜头",
                tip="null 使用 detection/calibration/output/calibrate.json",
            ),
            F(
                "roi",
                "配准 ROI",
                kind="str_null",
                section="图像配准",
                tip="x,y,width,height; null 用全图",
            ),
            F(
                "registration_max_dimension",
                "配准缩放上限",
                kind="int",
                section="图像配准",
                unit="px",
            ),
            F(
                "registration_use_gradient",
                "梯度域配准",
                kind="bool",
                section="图像配准",
            ),
            F(
                "min_registration_response",
                "最低配准响应",
                kind="float",
                section="图像配准",
                step=0.01,
            ),
            F("save_images", "保存采样图像", kind="bool", section="图像配准"),
            F("speed_rpm", "速度", kind="int", section="运动", unit="rpm"),
            F(
                "timeout_seconds",
                "运动超时",
                kind="float",
                section="运动",
                unit="s",
                step=0.5,
            ),
            F(
                "position_tolerance_mm",
                "到位容差",
                kind="float",
                section="运动",
                unit="mm",
                step=0.005,
            ),
            F(
                "max_step_mm",
                "单步最大距离",
                kind="float",
                section="运动",
                unit="mm",
                step=0.5,
            ),
            F(
                "max_reset_mm",
                "复位最大距离",
                kind="float",
                section="运动",
                unit="mm",
                step=1.0,
            ),
            F(
                "x_limits",
                "X 软限位",
                kind="vec2_null",
                section="运动",
                unit="mm",
                tip="[min, max]; null 不限制",
            ),
            F("y_limits", "Y 软限位", kind="vec2_null", section="运动", unit="mm"),
            camera_name_field(),
            camera_index_field(),
            *frame_size_fields(),
            F(
                "camera_startup_discard_frames",
                "开启相机丢弃帧数",
                kind="int",
                section="相机",
            ),
            F("capture_discard_frames", "采集前丢弃帧数", kind="int", section="相机"),
            F(
                "settle_seconds",
                "运动后稳定等待",
                kind="float",
                section="相机",
                unit="s",
                step=0.1,
            ),
            F("keep_camera_autofocus", "保留相机自动对焦", kind="bool", section="相机"),
            *stage_serial_fields(),
            F(
                "output_root",
                "输出根目录",
                section="输出",
                tip="每次运行在其下新建时间戳子目录",
            ),
        ],
    ),
    TaskSpec(
        id="zoom_transform",
        nav_label="Zoom 像素变换",
        glyph="⇱",
        title="双 Zoom 像素坐标变换标定",
        subtitle="保持相机和棋盘格不动，在两个 Zoom 下拟合双向像素矩阵，并计算各自的 mm/px。",
        script=SCRIPTS["zoom_transform"],
        config=CONFIGS["zoom_transform"],
        run_note=(
            "两次拍摄期间严禁移动相机、标定板或位移台。每档预览按 SPACE/ENTER 检测并接受，"
            "Q/ESC 取消；只有质量检查通过后才更新 calibrate.json。"
        ),
        fields=[
            F("source_zoom", "源 Zoom", kind="int", section="镜头位置"),
            F("target_zoom", "目标 Zoom", kind="int", section="镜头位置"),
            F("lens_device", "LensConnect 设备号", kind="int_null", section="镜头位置"),
            F("lens_no_init", "禁止自动初始化电机", kind="bool", section="镜头位置"),
            F(
                "lens_settle_seconds",
                "镜头稳定等待",
                kind="float",
                section="镜头位置",
                unit="s",
                step=0.1,
            ),
            F("board_cols", "棋盘内角点列数", kind="int", section="棋盘格"),
            F("board_rows", "棋盘内角点行数", kind="int", section="棋盘格"),
            F(
                "square_size_mm",
                "棋盘单格边长",
                kind="float",
                section="棋盘格",
                unit="mm",
                step=0.1,
                tip="相邻棋盘内角点的实际距离，用于计算两个 Zoom 的 mm/px",
            ),
            camera_name_field(),
            camera_index_field(),
            *frame_size_fields(),
            F(
                "camera_startup_discard_frames",
                "开启相机丢弃帧数",
                kind="int",
                section="相机",
            ),
            F("capture_discard_frames", "拍摄前丢弃帧数", kind="int", section="相机"),
            F("keep_camera_autofocus", "保留相机自动对焦", kind="bool", section="相机"),
            F(
                "capture_now",
                "立即抓拍",
                kind="bool",
                section="相机",
                tip="false: 每档 zoom 显示预览并等待确认",
            ),
            F(
                "source_image",
                "源 Zoom 离线图",
                kind="str_null",
                section="离线重算",
                tip="与目标图同时填写时跳过相机和镜头控制",
            ),
            F("target_image", "目标 Zoom 离线图", kind="str_null", section="离线重算"),
            F(
                "calibration",
                "标定汇总文件",
                kind="str_null",
                section="拟合",
                tip="null 使用 detection/calibration/output/calibrate.json",
            ),
            F(
                "ransac_threshold_px",
                "RANSAC 内点阈值",
                kind="float",
                section="拟合",
                unit="px",
                step=0.1,
            ),
            F("ransac_iterations", "RANSAC 最大迭代", kind="int", section="拟合"),
            F(
                "ransac_confidence",
                "RANSAC 置信度",
                kind="float",
                section="拟合",
                step=0.001,
            ),
            F(
                "min_inlier_ratio",
                "最小内点比例",
                kind="float",
                section="拟合",
                step=0.05,
            ),
            F(
                "max_inlier_rmse_px",
                "最大内点 RMSE",
                kind="float",
                section="拟合",
                unit="px",
                step=0.1,
            ),
            F(
                "output_dir",
                "输出目录",
                section="输出",
                tip="每次运行在 working_data 下建立时间戳目录",
            ),
        ],
    ),
    TaskSpec(
        id="mosaic",
        nav_label="PCB拍照",
        glyph="⊞",
        title="PCB 全图/局部图拍照",
        subtitle="小 Zoom 用四个白块自动计算 PCB 尺寸并拍摄全局图，再映射到大 Zoom 后自动蛇形拍摄局部图。",
        script=SCRIPTS["mosaic"],
        config=CONFIGS["capture"],
        run_note="无交互窗口。无需输入 PCB 长宽；focus/iris 自动读取对应 Zoom 的 PCB 自动对焦结果。请确保小 Zoom 画面能看到四个角上的白色方块。",
        fields=[
            F(
                "capture_margin_mm",
                "右/下拍摄余量",
                kind="float",
                section="局部图范围",
                unit="mm",
                step=0.5,
                tip="只在 PCB 右边和下边之外额外覆盖的距离；左边和上边不增加余量",
            ),
            F(
                "overlap_fraction",
                "最小重叠率",
                kind="float",
                section="局部图范围",
                step=0.05,
                tip="相邻帧最小重叠比例, 0.2~0.95",
            ),
            F(
                "small_zoom",
                "Zoom",
                kind="int",
                section="全图",
                tip="focus/iris 从同 Zoom 的 PCB 自动对焦结果读取",
            ),
            F(
                "large_zoom",
                "Zoom",
                kind="int",
                section="局部图",
                tip="focus/iris 从同 Zoom 的 PCB 自动对焦结果读取",
            ),
            F(
                "large_target_pixel",
                "目标像素",
                kind="vec2",
                section="局部图",
                unit="px",
                step=1.0,
                tip="[u, v] 左上白块右下角在大 Zoom 画面中的对齐位置",
            ),
            F(
                "white_block_threshold",
                "白块灰度阈值",
                kind="int",
                section="白块识别",
                tip="1~255；布局不合理时程序会自动逐级降低阈值重试",
            ),
            F(
                "white_block_min_area_px",
                "白块最小面积",
                kind="float",
                section="白块识别",
                unit="px²",
                step=50.0,
            ),
            F(
                "white_block_max_area_fraction",
                "白块最大面积占比",
                kind="float",
                section="白块识别",
                step=0.01,
                tip="相对整幅图面积，用于排除大面积白色背景",
            ),
            F(
                "white_block_min_square_ratio",
                "白块最小方形度",
                kind="float",
                section="白块识别",
                step=0.05,
                tip="短边/长边，越接近 1 越方正",
            ),
            F(
                "white_block_min_fill_ratio",
                "白块最小填充率",
                kind="float",
                section="白块识别",
                step=0.05,
            ),
            F(
                "white_block_morph_kernel",
                "形态学核尺寸",
                kind="int",
                section="白块识别",
                unit="px",
                tip="必须为正奇数，用于清除小噪声和填补小孔",
            ),
            F(
                "global_crop_padding_px",
                "全局图裁剪留边",
                kind="int",
                section="全图",
                unit="px",
                tip="正值向外留边；负值从四个白块内侧角向内收缩裁剪",
            ),
            F("lens_device", "LensConnect 设备号", kind="int_null", section="镜头"),
            F("lens_no_init", "禁止自动初始化电机", kind="bool", section="镜头"),
            F(
                "lens_settle_seconds",
                "镜头移动等待",
                kind="float",
                section="镜头",
                unit="s",
                step=0.1,
            ),
            F(
                "calibration",
                "标定汇总文件",
                kind="str_null",
                section="标定",
                tip="null 用 detection/calibration/output/calibrate.json",
            ),
            F(
                "allow_outside_image",
                "允许目标像素超出图像",
                kind="bool",
                section="标定",
            ),
            F("save_raw", "保存原始图", kind="bool", section="采集"),
            F(
                "output_dir",
                "输出目录",
                section="采集",
                tip="每次运行新建时间戳子目录, 必须位于 working_data 内",
            ),
            camera_name_field(),
            camera_index_field(),
            *frame_size_fields(),
            F("keep_camera_autofocus", "保留相机自动对焦", kind="bool", section="相机"),
            F(
                "camera_startup_discard_frames",
                "开启相机丢弃帧数",
                kind="int",
                section="相机",
            ),
            F("capture_discard_frames", "采集前丢弃帧数", kind="int", section="相机"),
            F(
                "capture_delay_seconds",
                "拍照前延迟",
                kind="float",
                section="相机",
                unit="s",
                step=0.1,
            ),
            *stage_serial_fields(),
            F(
                "speed_rpm",
                "位移台速度",
                kind="int",
                section="运动",
                unit="rpm",
                tip="控制拍照网格移动与回程的位移台转速",
            ),
            F(
                "timeout_seconds",
                "移动超时",
                kind="float",
                section="运动",
                unit="s",
                step=0.5,
            ),
            F(
                "position_tolerance_mm",
                "到位容差",
                kind="float",
                section="运动",
                unit="mm",
                step=0.005,
            ),
            F(
                "max_move_mm",
                "定点移动上限",
                kind="float",
                section="运动",
                unit="mm",
                step=1.0,
                tip="白块居中和大 Zoom 角点对齐时单次相对移动的最大距离",
            ),
            F(
                "max_step_mm",
                "单格移动上限",
                kind="float",
                section="运动",
                unit="mm",
                step=1.0,
                tip="需大于 0.8 倍视野对应的位移",
            ),
            F(
                "max_return_mm",
                "回程移动上限",
                kind="float",
                section="运动",
                unit="mm",
                step=5.0,
                tip="需大于整块 PCB 对角线行程",
            ),
            F(
                "x_limits",
                "X 软限位",
                kind="vec2_null",
                section="运动",
                unit="mm",
                tip="[minimum, maximum]; null 不限制",
            ),
            F("y_limits", "Y 软限位", kind="vec2_null", section="运动", unit="mm"),
        ],
    ),
]

# The board task remains available to non-GUI workflows but is intentionally
# omitted from the calibration workspace.
GUI_HIDDEN_TASK_IDS = frozenset(("board",))


def task_by_id(task_id: str) -> TaskSpec | None:
    for spec in TASKS:
        if spec.id == task_id:
            return spec
    return None
